language: node_js
node_js: node

deploy:
    provider: elasticbeanstalk
    region: 'eu-central-1'
    app: 'ScreentersDockerFinal'
    env: 'screentersdockerfinal-env'
    bucket_name: 'elasticbeanstalk-eu-central-1-284271987787'
    bucket_path: 'docker'
    access_key_id: "AKIAUEL7OJRFTJX3DXQ4"
    secret_access_key: "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"